# Generated by Django 5.2.4 on 2025-07-31 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gasto_pagobartender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('credito', 'Crédito/Fiado'), ('mixto', 'Pago Mixto'), ('compartido', 'Pago Compartido')], default='efectivo', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_compartidos', to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMixto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_mixto', to='core.venta')),
            ],
        ),
    ]
