# Generated by Django 5.2.4 on 2025-07-31 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_venta_metodo_pago_pagocompartido_pagomixto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocontable',
            name='venta_relacionada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.venta'),
        ),
    ]
