# Generated by Django 5.2.4 on 2025-07-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_movimientocontable_venta_relacionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
