# Generated by Django 5.2.4 on 2025-08-04 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_producto_precio_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Autorización'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('procesada', 'Procesada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('movimiento_reversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movimientocontable')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
