# Generated by Django 5.2.4 on 2025-08-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_notificacion_producto'),
    ]

    operations = [
    ]
