# Generated by Django 5.2.4 on 2025-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_limpiar_ventas_corruptas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='movimiento_contable_creado',
            field=models.BooleanField(default=False),
        ),
    ]
