# Generated by Django 5.2.4 on 2025-08-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_venta_movimiento_contable_creado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
    ]
