# Generated by Django 5.2.4 on 2025-08-13 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_detalleventa_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'ordering': ['-fecha_solicitud']},
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='movimiento_reversion',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='razon',
            field=models.CharField(choices=[('defectuoso', 'Producto defectuoso'), ('no_conforme', 'Cliente no conforme'), ('vencido', 'Producto vencido'), ('equivocado', 'Producto equivocado'), ('llegada_malo', 'Llegó dañado del proveedor'), ('caducado', 'Producto caducado en inventario'), ('roto_almacen', 'Se rompió en almacén'), ('calidad_baja', 'Calidad no aceptable'), ('otro', 'Otro motivo')], default='defectuoso', max_length=20),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Devolución de Cliente'), ('inventario', 'Devolución de Inventario')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='valor_recuperado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor que se recupera al inventario', max_digits=10),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta_origen',
            field=models.ForeignKey(blank=True, help_text='Venta de donde proviene el producto (solo para devoluciones de cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.venta'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='autorizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='comentario_admin',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('procesada', 'Procesada')], default='pendiente', max_length=20),
        ),
    ]
