# Generated by Django 5.2.4 on 2025-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_devolucion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (opcional). Tamaño recomendado: 800x600px', null=True, upload_to='productos/'),
        ),
    ]
