# Generated by Django 5.2.4 on 2025-08-14 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(help_text='NIT del proveedor', max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('contacto_principal', models.CharField(blank=True, max_length=100)),
                ('forma_pago_preferida', models.CharField(choices=[('contado', 'Contado'), ('credito_15', 'Crédito 15 días'), ('credito_30', 'Crédito 30 días'), ('credito_45', 'Crédito 45 días'), ('credito_60', 'Crédito 60 días')], default='contado', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('costo', 'Costo/Inversión')], max_length=10),
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('tipo_factura', models.CharField(choices=[('compra', '🛒 Compra de Inventario'), ('servicio', '🔧 Servicio'), ('gasto', '💸 Gasto Operativo')], default='compra', max_length=20)),
                ('fecha_factura', models.DateField(help_text='Fecha que aparece en la factura')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Cuándo se registró en el sistema')),
                ('fecha_recepcion', models.DateTimeField(blank=True, help_text='Cuándo se recibió la mercancía', null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, help_text='Cuándo se pagó', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('recibida', '📦 Recibida'), ('pagada', '✅ Pagada'), ('anulada', '❌ Anulada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_factura', models.FileField(blank=True, help_text='PDF o imagen de la factura', null=True, upload_to='facturas/compras/')),
                ('inventario_actualizado', models.BooleanField(default=False, help_text='Si ya se sumó al inventario')),
                ('movimiento_contable_creado', models.BooleanField(default=False, help_text='Si ya se registró en contabilidad')),
                ('pagada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_pagadas', to=settings.AUTH_USER_MODEL)),
                ('recibida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_registradas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'ordering': ['-fecha_factura', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.facturacompra')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Número de cheque, referencia de transferencia, etc.', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.facturacompra')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
