# Generated by Django 5.2.4 on 2025-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_abonodeuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_factura',
            field=models.DateTimeField(help_text='Fecha y hora que aparece en la factura'),
        ),
    ]
