# Generated by Django 5.2.4 on 2025-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_facturacompra_fecha_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Deuda', 'verbose_name_plural': 'Deudas'},
        ),
        migrations.AddField(
            model_name='deuda',
            name='total_abonado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se actualiza automáticamente con los abonos', max_digits=10, verbose_name='Total Abonado'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='monto_adeudado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Adeudado'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='nombre_cliente',
            field=models.CharField(max_length=255, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='¿Está Pagado?'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='telefono_cliente',
            field=models.CharField(max_length=20, verbose_name='Teléfono del Cliente'),
        ),
    ]
