# Generated by Django 5.2.4 on 2025-08-21 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_deuda_options_deuda_total_abonado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCombinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Promo 2x1 Cervezas', 'Combo Whisky Completo'", max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la promoción')),
                ('tipo_combo', models.CharField(choices=[('combo', '🎁 Combo Fijo'), ('promocion', '🏷️ Promoción'), ('pack', '📦 Pack Cantidad')], default='combo', max_length=20)),
                ('precio_combo', models.DecimalField(decimal_places=2, help_text='Precio especial del combo', max_digits=10)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen promocional del combo', null=True, upload_to='combos/')),
                ('activo', models.BooleanField(default=True, help_text='Si está disponible para venta')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (0-100)', max_digits=5)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de la promoción', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la promoción', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Combinado',
                'verbose_name_plural': 'Productos Combinados',
                'ordering': ['-activo', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VentaCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al que se vendió (puede diferir del precio actual)', max_digits=10)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to='core.productocombinado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_vendidos', to='core.venta')),
            ],
            options={
                'verbose_name': 'Venta de Combo',
                'verbose_name_plural': 'Ventas de Combos',
            },
        ),
        migrations.CreateModel(
            name='ComponenteCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de este producto en el combo')),
                ('es_opcional', models.BooleanField(default=False, help_text='Si el cliente puede omitir este componente')),
                ('observaciones', models.CharField(blank=True, help_text='Notas especiales del componente', max_length=200)),
                ('producto', models.ForeignKey(help_text='Producto que forma parte del combo', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='core.productocombinado')),
            ],
            options={
                'verbose_name': 'Componente de Combo',
                'verbose_name_plural': 'Componentes de Combo',
                'unique_together': {('combo', 'producto')},
            },
        ),
    ]
