# Generated by Django 5.2.4 on 2025-08-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_productocombinado_ventacombo_componentecombo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Devolución', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='aplicado_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad devuelta al proveedor'),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='codigo_producto',
            field=models.CharField(blank=True, help_text='SKU o código del proveedor', max_length=50),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='factura_origen',
            field=models.ForeignKey(blank=True, help_text='Factura de donde proviene el producto (devoluciones de inventario/proveedor)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facturacompra'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='nota_credito_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nota de crédito del proveedor', max_digits=10),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='reembolso_cliente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dinero devuelto al cliente', max_digits=10),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='razon',
            field=models.CharField(choices=[('defectuoso', 'Producto defectuoso'), ('no_conforme', 'Cliente no conforme'), ('vencido', 'Producto vencido'), ('equivocado', 'Producto equivocado'), ('llegada_malo', 'Llegó dañado del proveedor'), ('caducado', 'Producto caducado en inventario'), ('roto_almacen', 'Se rompió en almacén'), ('calidad_baja', 'Calidad no aceptable'), ('defecto_fabricacion', 'Defecto de fabricación'), ('fecha_vencida', 'Producto llegó vencido'), ('cantidad_incorrecta', 'Cantidad incorrecta en factura'), ('producto_incorrecto', 'Producto incorrecto enviado'), ('otro', 'Otro motivo')], default='defectuoso', max_length=30),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Devolución de Cliente'), ('inventario', 'Devolución de Inventario'), ('proveedor', 'Devolución a Proveedor')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='venta_origen',
            field=models.ForeignKey(blank=True, help_text='Venta de donde proviene el producto (devoluciones de cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.venta'),
        ),
        migrations.CreateModel(
            name='InventarioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField(help_text='Cantidad que se agregó al inventario')),
                ('cantidad_actual', models.PositiveIntegerField(help_text='Cantidad que queda de esta factura')),
                ('precio_costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cantidad_devuelta_cliente', models.PositiveIntegerField(default=0)),
                ('cantidad_devuelta_proveedor', models.PositiveIntegerField(default=0)),
                ('cantidad_perdida', models.PositiveIntegerField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_generados', to='core.facturacompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_factura', to='core.producto')),
            ],
            options={
                'verbose_name': 'Inventario por Factura',
                'verbose_name_plural': 'Inventarios por Factura',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
